engines:
  brakeman:
    enabled: true
    exclude_paths:
    # Excluding User Flows tools since these are not loaded
    # except when explicitly called from the User Flow rake tasks
    - 'lib/user_flow_exporter.rb'
    - 'lib/rspec/formatters/user_flow_formatter.rb'
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 50
    exclude_paths:
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'app/forms/password_form.rb'
    - 'lib/user_flow_exporter.rb'
    - 'lib/rspec/formatters/user_flow_formatter.rb'
  eslint:
    enabled: true
  fixme:
    enabled: true
    exclude_paths:
    - 'public/build/bundle.js'
    - '.codeclimate.yml'
    config:
      strings:
      # Removed TODO from this list, as we want to allow TODOs in the codebase
      - FIXME
      - HACK
      - BUG
      - XXX
  pep8:
    enabled: true    
  reek:
    enabled: true
    exclude_paths:
    - 'spec/**/*'
    - 'db/migrate/*'
    - 'lib/user_flow_exporter.rb'
    - 'lib/rspec/formatters/user_flow_formatter.rb'
  rubocop:
    enabled: true
  scss-lint:
    enabled: true 
ratings:
  paths:
  - app/**
  - lib/**
  - '**.rb'
  - '**.go'
  exclude_paths:
    - 'lib/user_flow_exporter.rb'
    - 'lib/rspec/formatters/user_flow_formatter.rb'
