postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  database: upaya_<%= Rails.env %>
  port: 5432
  username: <%= ENV['DOCKER_DB_USER'] %>

defaults: &defaults
  host: <%= ENV['DOCKER_DB_HOST'] || 'localhost' %>
  pool: 5
  <<: *postgresql
  # timeout settings
  timeout: <%= Figaro.env.database_timeout.to_i %>
  reconnect: true
  connect_timeout: 2
  keepalives_idle: 10
  keepalives_interval: 10
  keepalives_count: 2
  checkout_timeout: 5
  reaping_frequency: 10
  variables:
    statement_timeout: 2500 # ms

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  database: <%= Figaro.env.database_name! %>
  username: <%= Figaro.env.database_username! %>
  host: <%= Figaro.env.database_host! %>
  password: <%= Figaro.env.database_password! %>
  pool: <%= (File.exist?('/etc/login.gov/info') && File.read('/etc/login.gov/info/role').chomp == 'worker') ? 26 : 5 %>
  sslmode: 'verify-full'
  sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
